### ISSUE TITLE
能更新一下依赖重新打包一下吗？

### ISSUE THREAD

**Issue by rachpt** [Sec-ant/gm-fetch#109]
vite-plugin-monkey 侧有个bug：https://github.com/lisonge/vite-plugin-monkey/issues/163
@sec-ant/gm-fetch 这个包引入了旧版本的代码，可能需要重新打包才能修复
![image](https://github.com/Sec-ant/gm-fetch/assets/25758867/c7da6278-8a5a-41ec-a32e-ae08d5d20e53)

**Comment by Sec-ant** [comment]
好，今天晚点，现在手头没电脑

**Comment by Sec-ant** [comment]
v1.2.1 已发布：https://www.npmjs.com/package/@sec-ant/gm-fetch/v/1.2.1
